require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative './kebetoo_pods'

platform :ios, '10.0'
target 'Kebetoo' do
  use_kebetoo_pods!

  config = use_native_modules!
  use_react_native!(:path => config['reactNativePath'])
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.79.0'})
  post_install do |installer|
    flipper_post_install(installer)
    react_native_share_menu_post_install(installer)
    iphoneos_post_install(installer)
  end
end

target 'ShareExtension' do
  use_react_native!
  use_kebetoo_share_extensions_pods!
end