require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative './kebetoo_pods'

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

platform :ios, '10.0'
target 'Kebetoo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  use_kebetoo_pods!

  target 'KebetooTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    react_native_share_menu_post_install(installer)
  end
end

target 'Kebetoo-tvOS' do
  # Pods for Kebetoo-tvOS

  target 'Kebetoo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal
end