const routes = {
  ONBARDING_NAV: 'route:onboarding_nav',
  SIGNIN: 'route:signin',
  SIGNUP: 'route:signup',
  ONBOARDING: 'route:onboarding',
  HOME_NAV: 'route:home_nav',
  HOME: 'tab:home',
  ROOMS: 'tab:rooms',
  NOTIFICATIONS: 'tab:notifications',
  STORIES: 'tab:stories',
  SEARCH: 'route:search',
  CREATE_POST: 'route:create_post',
  TABS_FAB: 'tab:tabs_fab',
  COMMENTS: 'route:comments',
  MANAGE_POSTS: 'route:manage_posts',
  MODAL_IMAGE: 'route:modal_image',
  MODAL_VIDEO: 'route:modal_video',
  USER_PROFILE: 'route:user_profile',
  SEARCH_POSTS: 'tab:search_posts',
  SEARCH_USERS: 'tab:search_users',
  CAMERA_ROLL_PICKER: 'route:camera_roll_picker',
  PROFILE: 'route:profile',
  EDIT_PROFILE: 'route:edit_profile',
  LANGUAGES: 'route:languages',
  CREATE_ROOM: 'route:create_room',
  ROOM: 'route:room',
};

export default routes;
